### ISSUE TITLE
Date parsing and timeout errors

### ISSUE THREAD

**Issue by jonrau1** [awslabs/amazon-neptune-tools#121]
Hello, I am working through two different bugs, I am not sure if they are related and can break the issues out for better tracking purposes if desired.

The first is an issue with handling datetimes, I stored dates as a String within the Graph, but they can vary between ISO8601 format to various different types of strftime or datetime, maybe even some Epoch timestamps. So the first error I encounter is related to that - **Is there a way to override this processing either on ES or within the Job?**

```
[ERROR] BulkIndexError: ('34 document(s) failed to index.', [{'update': {'_index': 'amazon_neptune', '_type': '_doc', '_id': 'c14df75bfb7c90c770ea0bf841169329', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [predicates.CreatedAt.value] of type [date] in document with id 'c14df75bfb7c90c770ea0bf841169329'. Preview of field's value: '2019-05-24 10:54:53.529000+00:00'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'failed to parse date field [2019-05-24 10:54:53.529000+00:00] with format [strict_date_optional_time||epoch_millis]', 'caused_by': {'type': 'date_time_parse_exception', 'reason': 'date_time_parse_exception: Failed to parse with all enclosed parsers'}}}
```

The next issues I run into are what appear to be transient timeout issues, I am unsure if they are related to any of the data types within the graph itself, we do have lists (and write them in as strings) as well as JSON docs (`.dumps`) that we write into the graph, again as strings. Sometimes the Lists are written as a stringified empty list (`[]`) - unsure if that is affecting it as well. **Is there a way to configure the export utility to treat everything as a string and stop trying to validate / transform the types?**

```

[kpl-daemon-0003] INFO com.amazonaws.services.kinesis.producer.LogInputStreamReader - [2021-03-15 19:29:07.463988] [0x00000023][0x00007f78c988d700] [info] [processing_statistics_logger.cc:129] (neptune-export-ee598750) Average Processing Time: 34.363128 ms
An error occurred while writing all nodes as JSON (Neptune Streams format) to stream. Elapsed time: 172 seconds
An error occurred while exporting all nodes. Elapsed time: 195 seconds
[main] INFO org.apache.tinkerpop.gremlin.driver.ConnectionPool - Signalled closing of connection pool on Host{address=neptunedbcrg.cluster-calvzb374vjl.us-east-1.neptune.amazonaws.com/10.199.1.175:8182, hostUri=wss://neptunedbcrg.cluster-calvzb374vjl.us-east-1.neptune.amazonaws.com:8182/gremlin} with core size of 5
An error occurred while exporting property graph. Elapsed time: 198 seconds
java.util.concurrent.ExecutionException: java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: {     "detailedMessage": "A timeout occurred within the script or was otherwise cancelled directly during evaluation of [24658221-460c-4835-a24e-0e5e36ff04c4]",     "code": "TimeLimitExceededException",     "requestId": "24658221-460c-4835-a24e-0e5e36ff04c4" }
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at com.amazonaws.services.neptune.propertygraph.io.ExportPropertyGraphJob.updateFileSpecificLabelSchemas(ExportPropertyGraphJob.java:135)
at com.amazonaws.services.neptune.propertygraph.io.ExportPropertyGraphJob.lambda$export$1(ExportPropertyGraphJob.java:114)
at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
at com.amazonaws.services.neptune.propertygraph.io.ExportPropertyGraphJob.export(ExportPropertyGraphJob.java:89)
at com.amazonaws.services.neptune.propertygraph.io.ExportPropertyGraphJob.lambda$execute$0(ExportPropertyGraphJob.java:64)
at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:74)
at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:67)
at com.amazonaws.services.neptune.propertygraph.io.ExportPropertyGraphJob.execute(ExportPropertyGraphJob.java:63)
at com.amazonaws.services.neptune.ExportPropertyGraph.lambda$run$0(ExportPropertyGraph.java:109)
at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
at com.amazonaws.services.neptune.ExportPropertyGraph.run(ExportPropertyGraph.java:85)
at com.amazonaws.services.neptune.export.NeptuneExportRunner.run(NeptuneExportRunner.java:44)
at com.amazonaws.services.neptune.NeptuneExportCli.main(NeptuneExportCli.java:48)
Caused by: java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: {     "detailedMessage": "A timeout occurred within the script or was otherwise cancelled directly during evaluation of [24658221-460c-4835-a24e-0e5e36ff04c4]",     "code": "TimeLimitExceededException",     "requestId": "24658221-460c-4835-a24e-0e5e36ff04c4" }
at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
at org.apache.tinkerpop.gremlin.driver.ResultSet.one(ResultSet.java:119)
at org.apache.tinkerpop.gremlin.driver.ResultSet$1.hasNext(ResultSet.java:171)
at org.apache.tinkerpop.gremlin.driver.ResultSet$1.next(ResultSet.java:178)
at org.apache.tinkerpop.gremlin.driver.ResultSet$1.next(ResultSet.java:165)
at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal$TraverserIterator.next(DriverRemoteTraversal.java:146)
at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal$TraverserIterator.next(DriverRemoteTraversal.java:131)
at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal.nextTraverser(DriverRemoteTraversal.java:112)
at org.apache.tinkerpop.gremlin.process.remote.traversal.step.map.RemoteStep.processNextStart(RemoteStep.java:80)
at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:205)
at org.apache.tinkerpop.gremlin.process.traversal.Traversal.forEachRemaining(Traversal.java:273)
at com.amazonaws.services.neptune.propertygraph.NodesClient.queryForValues(NodesClient.java:103)
at com.amazonaws.services.neptune.propertygraph.io.ExportPropertyGraphTask.call(ExportPropertyGraphTask.java:86)
at com.amazonaws.services.neptune.propertygraph.io.ExportPropertyGraphTask.call(ExportPropertyGraphTask.java:29)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: {     "detailedMessage": "A timeout occurred within the script or was otherwise cancelled directly during evaluation of [24658221-460c-4835-a24e-0e5e36ff04c4]",     "code": "TimeLimitExceededException",     "requestId": "24658221-460c-4835-a24e-0e5e36ff04c4" }
at org.apache.tinkerpop.gremlin.driver.Handler$GremlinResponseHandler.channelRead0(Handler.java:259)
at org.apache.tinkerpop.gremlin.driver.Handler$GremlinResponseHandler.channelRead0(Handler.java:198)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at org.apache.tinkerpop.gremlin.driver.Handler$GremlinSaslAuthenticationHandler.channelRead0(Handler.java:124)
at org.apache.tinkerpop.gremlin.driver.Handler$GremlinSaslAuthenticationHandler.channelRead0(Handler.java:68)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at org.apache.tinkerpop.gremlin.driver.handler.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:89)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1526)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
... 1 more
An error occurred while exporting from Neptune: java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: {     "detailedMessage": "A timeout occurred within the script or was otherwise cancelled directly during evaluation of [24658221-460c-4835-a24e-0e5e36ff04c4]",     "code": "TimeLimitExceededException",     "requestId": "24658221-460c-4835-a24e-0e5e36ff04c4" }
```

**Comment by shoegazerstella** [comment]
I have the same issue related to the timeout.
Any update on how to solve this? Is there some parameter to add to the neptune-export command or the json file? Should I modify the timeout on neptune directly?
thanks!

**Comment by Cole-Greer** [comment]
Hi @jonrau1, I have done an investigation into these errors, the first error appears to arise from ElasticSearch failing to index the incoming datestrings of various formats. This is not the result of any type conversion happening during the export run. If any date property has a type of string, the exported value will also have be a string. To solve this, a user would either have to structure their data to only include the date strings in the formats expected by elasticsearch (strict_date_optional_time||epoch_millis) or configure their elasticsearch deployment to accept a broader range of formats.

The second error could have many underlying causes. I believe for some users the timeout issue will be resolved by [this](https://github.com/awslabs/amazon-neptune-tools/pull/274) fix. For anyone still experiencing timeout issues, I would recommend starting by checking that `neptune_query_timeout` in the neptune instance parameter group is sufficiently large. The export tool uses long running queries which will timeout if this is not configured correctly. It does not appear to me that the timeout is related to type validation or transformation. Export tool does perform schema inference on exported data but the bulk of this cost takes place after all of the nodes/edges have been extracted from neptune. The timeout shown above is taking place during the query execution in neptune to extract all of the nodes from the graph. The likely causes of this are an insufficiently configured timeout or batch job having too few resources allocated to it.

Please feel free to reach out if you're still having any trouble with these errors. I would like to close this issue if the recommendations above resolve everyone's errors.
