### ISSUE TITLE
NeptuneIAMConnection Fails | gremlinpython no longer uses tornado

### ISSUE THREAD

**Issue by demerichbl** [awslabs/amazon-neptune-tools#129]
```
Traceback (most recent call last):
  File "osm_ground_truth.py", line 26, in <module>
    from neptune_python_utils.neptune_iam import NeptuneIAMConnection
  File "/usr/local/lib/python3.6/site-packages/neptune_python_utils/neptune_iam.py", line 1, in <module>
    from neptune_python_utils.gremlin_utils import GremlinUtils
  File "/usr/local/lib/python3.6/site-packages/neptune_python_utils/gremlin_utils.py", line 31, in <module>
    from tornado.httpclient import HTTPError
ModuleNotFoundError: No module named 'tornado'
```

**Comment by iansrobinson** [comment]
I think we need to pin gremlin-python to < 3.5.0 at the moment until Neptune supports 3.5.0. I'll look into doing that.

**Comment by iansrobinson** [comment]
Closing this issue
