### ISSUE TITLE
Mixed int / double property types causes errors in export-pg-from-queries

### ISSUE THREAD

**Issue by HughBlayney** [awslabs/amazon-neptune-tools#175]
When exporting `elementMap`s of vertices where there exists a property where some nodes have values of `int` type and some of `double` type, I get the following error
```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.amazonaws.services.neptune.propertygraph.io.QueryJob.export(QueryJob.java:93)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
	at com.amazonaws.services.neptune.propertygraph.io.QueryJob.execute(QueryJob.java:52)
	at com.amazonaws.services.neptune.ExportPropertyGraphFromGremlinQueries.lambda$run$0(ExportPropertyGraphFromGremlinQueries.java:114)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
	at com.amazonaws.services.neptune.ExportPropertyGraphFromGremlinQueries.run(ExportPropertyGraphFromGremlinQueries.java:88)
	at com.amazonaws.services.neptune.export.NeptuneExportRunner.run(NeptuneExportRunner.java:53)
	at com.amazonaws.services.neptune.NeptuneExportCli.main(NeptuneExportCli.java:48)
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at com.amazonaws.services.neptune.propertygraph.schema.DataType$8.printTo(DataType.java:222)
	at com.amazonaws.services.neptune.propertygraph.io.JsonPropertyGraphPrinter.printProperty(JsonPropertyGraphPrinter.java:151)
	at com.amazonaws.services.neptune.propertygraph.io.JsonPropertyGraphPrinter.printProperty(JsonPropertyGraphPrinter.java:121)
	at com.amazonaws.services.neptune.propertygraph.io.JsonPropertyGraphPrinter.printProperties(JsonPropertyGraphPrinter.java:79)
	at com.amazonaws.services.neptune.propertygraph.io.QueryWriter.handle(QueryWriter.java:30)
	at com.amazonaws.services.neptune.propertygraph.io.QueryWriter.handle(QueryWriter.java:18)
	at com.amazonaws.services.neptune.propertygraph.io.QueryTask$ResultsHandler.handle(QueryTask.java:201)
	at com.amazonaws.services.neptune.propertygraph.io.QueryTask$ResultsHandler.handle(QueryTask.java:158)
	at com.amazonaws.services.neptune.propertygraph.io.QueryTask$StatusHandler.handle(QueryTask.java:222)
	at com.amazonaws.services.neptune.propertygraph.io.QueryTask.lambda$executeQuery$5(QueryTask.java:143)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.amazonaws.services.neptune.propertygraph.io.QueryTask.executeQuery(QueryTask.java:141)
	at com.amazonaws.services.neptune.propertygraph.io.QueryTask.lambda$call$1(QueryTask.java:89)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
	at com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
	at com.amazonaws.services.neptune.propertygraph.io.QueryTask.call(QueryTask.java:87)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
An error occurred while exporting from Neptune: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
```

This seems to only happen when exporting to json, and occurs both with or without the `--two-pass-analysis` flag.

## Minimal Example
A minimal example can be recreated by creating two nodes
```
v = g.addV('test1').property('testproperty', 0).id().next()
u = g.addV('test2').property('testproperty', 0.5).id().next()
```
and running an export that looks like
```
./bin/neptune-export.sh export-pg-from-queries -q result="g.V(<v_id>, <u_id>).elementMap()" ... --format json
```

From my perspective, it would be ideal if the query exporter didn't require a single type for values of one property, especially since Neptune itself doesn't enforce this constraint.

Relatedly: I'm using the json exporter since I can't figure out how to export column headings (the property keys) when exporting to csv. I'd be very grateful if you were able to point me in the direction of how to do this, and that would hopefully be a good short term solution to this problem.

Thank you for your time!

**Comment by iansrobinson** [comment]
Hi @HughBlayney 

Thanks for reporting this. I've reproduced the issue and incorporated a fix, and these changes have now been pushed to the repository.

When you export using export-pg, neptune-export will include the CSV headings, though I don't think it does this for export-pg-from-queries at the moment. 

In terms of casting to the narrowest type that supports all instances of a property value: this has been a characteristic of neptune-export from the outset.

I'll look into adding support for CSV headers for query results, and allowing passthru of raw datatypes. Unfortunately, I can't give any estimates of timelines for adding these features at the moment.

Kind regards

ian

**Comment by HughBlayney** [comment]
Hi @iansrobinson 

Thank you for fixing this so quickly! The changes fixed the problem and everything now works as expected.

I also appreciate the work on adding the CSV headers for query results. But for now, exporting to JSON is working well.

Best wishes,
Hugh
