### ISSUE TITLE
export-neptune-to-elasticsearch: "Elastic Search version less then 7.x is not supported. Current version - 1.0.0"

### ISSUE THREAD

**Issue by carlcelliers-woodside** [awslabs/amazon-neptune-tools#185]
Hi, 

I have created an Opensearch domain using the default version of 1.0.0. 

The export-neptune-to-elasticsearch stack creates a kinesis-to-elasticsearch lambda which fails when run with the error: "Elastic Search version less then 7.x is not supported. Current version - 1.0.0"

Please update the code to use Opensearch instead of Elasticsearch.

**Comment by iansrobinson** [comment]
Hi @carlcelliers-woodside 

The export-neptune-to-elasticsearch stack reuses code provided by the Amazon Neptune-to-OpenSearch solution (https://docs.aws.amazon.com/neptune/latest/userguide/full-text-search-cfn-create.html) to publish data to OpenSearch. As per the notes there:

"When integrating with Amazon OpenSearch Service, Neptune requires Elasticsearch version 7.1 or higher rather than OpenSearch version 1.0. Neptune is not currently compatible with OpenSearch version 1.0."

Kind regards

ian

**Comment by williamjv** [comment]
Hello,

Reviewing this thread it appears adjustments were made for exporting to OpenSearch on January 31st?   Please correct me if I am wrong as I also am having the issue.  The link provided earlier appears to no longer state "Neptune is not currently compatible with OpenSearch...".

Here is what the logs are showing.

```
[ERROR] Exception: Elastic Search version less than 7.x is not supported. Current version - 1.2.4
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 236, in load_module
    return load_compiled(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 191, in load_compiled
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "kinesis_to_elasticsearch.py", line 71, in <module>
  File "kinesis_to_elasticsearch.py", line 69, in get_handler_instance
  File "kinesis_to_elasticsearch.py", line 58, in get_handler_instance
  File "/opt/python/neptune_to_es/neptune_gremlin_es_handler.py", line 109, in __init__
    super().__init__()
  File "/opt/python/neptune_to_es/neptune_to_es_handler.py", line 236, in __init__
    __initial_setup__(self.__get_es_client())
  File "/opt/python/neptune_to_es/neptune_to_es_handler.py", line 121, in __initial_setup__
    es_helper.validate_es_version(es_client)
  File "/opt/python/neptune_to_es/es_helper.py", line 202, in validate_es_version
    raise Exception("Elastic Search version less than 7.x is not supported. Current version - {}"
    ```

Thank you,
William

**Comment by gopuneet** [comment]
@williamjv Thank you for reporting the template inconsistency between the S3 location and github source. 

We have updated the S3 template file ([link](https://s3.amazonaws.com/aws-neptune-customer-samples/neptune-sagemaker/cloudformation-templates/export-neptune-to-elasticsearch/export-neptune-to-elasticsearch.json)) with the latest content of [export-neptune-to-elasticsearch.json](https://github.com/awslabs/amazon-neptune-tools/blob/master/export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json) file in GitHub after #218.
