### ISSUE TITLE
TypeError when trying to export data from Kinesis to ElasticSearch

### ISSUE THREAD

**Issue by TomD-Woodside** [awslabs/amazon-neptune-tools#221]
export-neptune-to-elasticsearch template, ES version 7.10. 

Happens when using 'release_2022_04_19' for the lambda artefacts. This bug does not occur when using 'release_2021_08_23'.

[ERROR] TypeError: unsupported operand type(s) for /: 'str' and 'float'
Traceback (most recent call last):
  File "kinesis_to_elasticsearch.py", line 150, in lambda_bulk_handler
  File "/opt/python/neptune_to_es/neptune_to_es_handler.py", line 495, in handle_records
    actions = self.__generate_aggregated_es_actions__(records)
  File "/opt/python/neptune_to_es/neptune_to_es_handler.py", line 429, in __generate_aggregated_es_actions__
    aggregate_map = aggregator.aggregate_records(records)
  File "/opt/python/aggregator/es_aggregator.py", line 138, in aggregate_records
    for record in records:
  File "/opt/python/neptune_to_es/neptune_gremlin_es_handler.py", line 220, in filter_records
    record_value = get_date_time_from_millis(record_value)
  File "/opt/python/neptune_to_es/es_helper.py", line 264, in get_date_time_from_millis
    return dt.fromtimestamp(time_in_millis / 1000.0).isoformat("T", "milliseconds")

**Comment by triggan** [comment]
The versions of lambda artefacts mentioned are from Python3.6.  All latest versions support Python3.9 (and soon a newer version of Python).  Closing this as a stale issue, but please re-open if you come across this same exception.  If you encounter this exception, it may be helpful to include the related record that is not being parsed correctly.
